project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404
from core import views as core_views

handler404 = core_views.handler404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
]

webapp/urls.py
# webapp/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index_page_view, name='index'),
    path('contact', views.contact_page_view, name='contact'),
]

core/models/user.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import EmailValidator


class CustomUser(AbstractUser):
    email = models.EmailField(
        error_messages={'unique': 'A user with that email already exists.'},
        help_text='Required. 254 characters or fewer.', max_length=254,
        unique=True, verbose_name='email address',
        validators=[EmailValidator])
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    class Meta:
        db_table = 'users'

webapp/models.py
from django.db import models

# Create your models here.

webapp/forms.py
from django import forms


class ContactForm(forms.Form):
    your_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Your name'}))
    your_email = forms.EmailField(max_length=100, widget=forms.EmailInput(attrs={'placeholder': 'Your email'}))
    # your_number = forms.CharField(max_length=12, widget=forms.TextInput(attrs={'placeholder': 'Your number'}))   
    your_message = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Your message'}))

core/views.py
from django.shortcuts import render


def handler404(request):
        data = {}
        return render(request,'core/404.html', data)

webapp/views.py
import random

from django.shortcuts import render, redirect
from django.core.mail import send_mail

from .forms import ContactForm
from project.settings import EMAIL_HOST_USER


def index_page_view(request):
    context = {}

    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = ContactForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            context['form_success'] = True
            recipients = [EMAIL_HOST_USER]
            if request.POST.get('sith') != request.POST.get('jedi'):
                send_mail(
                    "Spam caught from {}".format(form.cleaned_data['your_name']),
                    form.cleaned_data['your_message'],
                    EMAIL_HOST_USER,
                    recipients
                )
            else:
                recipients.append(form.cleaned_data['your_email'])
                send_mail(
                    "New contact form submitted by {}".format(form.cleaned_data['your_name']),
                    form.cleaned_data['your_message'],
                    EMAIL_HOST_USER,
                    recipients
                )
            return redirect('/contact')
        else:
            context['form_error'] = True

    context['form'] = ContactForm()
    context['a'] = random.randint(1, 20)
    context['b'] = random.randint(1, 20)
    context['jedi'] = context['a'] + context['b']

    return render(request, 'webapp/index.html', context)


def contact_page_view(request):
    context = {}

    return render(request, 'webapp/contact.html', context)


# def about_page_view(request):
#     context = {}
#     return render(request, 'webapp/about.html', context)

webapp/templates/webapp/about.html
{% extends "webapp/layouts/base.html" %}
{% load static %}

{% block headers %}
  <link rel="stylesheet" type="text/css" href="{% static 'webapp/css/about.css' %}" />
{% endblock %}

{% block title %}
  About Gary
{% endblock %}

{% block body %}

<div id="about-text">

  <p>
    Gary Burgmann is a student software engineer and currently has a job working with Angular and Laravel. He really loves building his own projects with Python, Django, NodeJS and ReactJS on the side.
  </p>
  <p class="text-center">
    You can find more information regarding all things Gary at: 
  </p>
  <p class="text-center">
    <a class="fab fa-gitlab" href="https://gitlab.com/garyburgmann"> GitLab </a> &nbsp;
    <a class="fab fa-github" href="https://github.com/garyburgmann"> GitHub</a> &nbsp;
    <a class="fab fa-linkedin" href="https://www.linkedin.com/in/garyburgmann/"> LinkedIn</a> &nbsp;
  </p>

</div>

{% endblock %}

webapp/templates/webapp/contact.html
{% extends "webapp/layouts/base.html" %}
{% load static %}

{% block headers %}
  <link rel="stylesheet" type="text/css" href="{% static 'webapp/css/contact.css' %}" />
{% endblock %}

{% block title %}
  Contact Submitted
{% endblock %}

{% block body %}

<div class="container-light">
  <div class="section-text">

    <p class="text-center">
      Thanks for dropping me a line :) I'll be in touch soon.
    </p>
    <p class="text-center">
      <a class="btn btn-dark" role="button" href="/">Back</a>
    </p>

  </div>
</div>

{% endblock %}

webapp/templates/webapp/index.html
{% extends "webapp/layouts/base.html" %}
{% load static %}

{% block headers %}
  <link rel="stylesheet" type="text/css" href="{% static 'webapp/css/index.css' %}" />
{% endblock %}

{% block title %}
  Home
{% endblock %}

{% block body %}

<div id="home" class="container-light">
  <div class="section-text">

    <p>
      This site was last updated 01-02-2019.
    </p>

    <p>
      Currently, most of my work is proprietary,
      but I look forawrd to sharing my new learnings as I investigate serverless deployments
      with Zappa and the Serverless framework, the AWS ecosystem (in particular RDS to use 
      with serverless deployments), managing authentication with third party providers such
      as Firebase and Auth0, Docker gotchas (e.g. adding secrets to docker-compose...trickier
      to manage than simple .env files!), and my dive into deep learning (with Udacity).
    </p>

    <p>
      Please do not be perturbed by my recent drop in GitHub/GitLab activity. I recently got
      married (November 2018), so I had a 4-week break and then started working at Griffith where
      we run a privately hosted GitLab server, logging in with my staff account. Rest assured,
      I am pushing bucketloads of code every day, I just can't share it with you! I did write a
      nice little paginator for use with SQL-Alchemy though, perhaps I could learn to deploy that
      to PyPy and share that process :)
    </p>

    <p>
      Until then ..... <a href="#about" >About Me</a>
    </p>

  </div>
</div>

<div id="about" class="container-dark">
  <div class="section-text">

    <p>
      Gary Burgmann is a student software engineer and is currently working for Griffith Univeristy's 
      eResearch team as a developer. His current focus at work is rebuilding a clinical trials
      application, from Plone to a SPA architecture of ReactJS/Pyramid/MySQL, where his role is to
      develop the API in Pyramid. It has been an interesting learning experience to apply continous
      integration with a Docker & Jenkins pipeline. 
    </p>

    <p>
      He is also developing a web application for the Queensland State Archives to assist
      in automatic reconstruction of document pieces, using Django as the framework and the
      JavaScript library Konva for the manipulation of individual pieces where needed. Previously
      he has also worked as a developer on a large project with an Angular/Laravel/MySQL stack.
    </p>

    <p>
      Outside of work, he thoroughly enjoys working within the Django ecosystem and is currently
      developing two personal projects utilising the framework. He has previously deployed applications
      to Digital Ocean (including this one!), one of which was a ReactJS/ExpressJS/Mongo stack for
      his wedding to receive guest RSVPs and provide information for guests. Moving forward, his aim
      is to utilize serverless deployments with AWS, implementing the Serverless framework for NodeJS
      or Zappa for Django/Flask projects, a SPA architecture consisting of server-side rendered ReactJS
      with NextJS, and Amazon's Relational Database Service with Postgres, as his stack of choice. He
      is also very keen to learn more data science related techniques, having only briefly used SciKit
      learn modules for high level machine learning tasks in the past, now currently diving into PyTorch
      with Udacity.
    </p>

    <p class="text-center">
      You can find more information regarding all things Gary at: 
    </p>
    <p class="text-center">
      <a class="fab fa-gitlab social-link" href="https://gitlab.com/garyburgmann"> GitLab </a> &nbsp;
      <a class="fab fa-github social-link" href="https://github.com/garyburgmann"> GitHub</a> &nbsp;
      <a class="fab fa-linkedin social-link" href="https://www.linkedin.com/in/garyburgmann/"> LinkedIn</a> &nbsp;
    </p>

  </div>
</div>

<div id="contact" class="container-light container">
  <div class="section-text row">
    <div class="col-12 text-center">
      
      <p>
        Get in touch with Gary
      </p>

      <form action="/" method="POST">
        {% csrf_token %}
        <div class="form-group">
          <input name="your_name" type="text" class="form-control" id="id_your_name" placeholder="Your name" required>
        </div>
        <div class="form-group">
          <input name="your_email" type="email" class="form-control" id="id_your_email" placeholder="Your email" required>
          <!-- <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small> -->
        </div>

        <!-- <div class="form-group">
          <input name="your_number" type="text" class="form-control" id="id_your_number" placeholder="Your number">
        </div> -->

        <div class="form-group">
          <textarea name="your_message" rows="5" class="form-control" placeholder="Your message" id="id_your_message" required></textarea>
        </div>

        <div class="form-group">
          <input class="form-control" name="sith" type="text" placeholder="{{ a }} + {{ b }} = ?">
        </div>

        <div id="venus" class="form-group">
          <input class="form-control" name="jedi" type="text" value="{{ jedi }}">
        </div>

        <button type="submit" class="btn btn-dark btn-block">Submit</button>
      </form>

      {% if form_success %}
      <p class="success-message">
        Form submitted successfully
      </p>
      {% endif %}
      
    </div>
  </div>
</div>



{% endblock %}

webapp/templates/webapp/layouts/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'webapp/css/layouts/base.css' %}" />
    <script type="text/javascript" src="{% static 'webapp/js/layouts/base.js' %}"></script>

    {% block headers %}
    {% endblock %}
    
    <title>
      {% block title %}
      My Site!
      {% endblock %}
    </title>

  </head>
  <body>
    <div class="cover">

      <nav class="navbar navbar-expand-md justify-content-end layer">

        <button class="navbar-toggler navbar-dark" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active justify-content-end">
              <a class="nav-link base-nav" href="/">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active base-nav" href="#about">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active base-nav" href="#contact">Contact</a>
            </li>
          </ul>
        </div>

      </nav>

      <div class="jumbotron jumbotron-fluid layer">
        <div class="container text-center">

          <h1 id="header-name" class="display-4">Gary Burgmann</h1>
          <hr>
          <p class="lead">Full stack web developer. Python and JavaScript fan.</p>

        </div>
      </div>

    </div>

    {% block body %}
    <div>
      <h1 >Hello, world!</h1>
    </diV>
    
    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>